// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BojoweZaby.Migrations
{
    [DbContext(typeof(AppDbContext))]
    [Migration("20250531222213_AccountUpdate")]
    partial class AccountUpdate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BojoweZaby.Models.AccountModel", b =>
                {
                    b.Property<string>("AccountId")
                        .HasColumnType("TEXT");

                    b.Property<int>("AccountTypeName")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Username")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("AccountId");

                    b.ToTable("AccountModel");
                });

            modelBuilder.Entity("BojoweZaby.Models.FrogModel", b =>
                {
                    b.Property<string>("FrogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("AccountId")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ClassId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("HP")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("FrogId");

                    b.HasIndex("AccountId");

                    b.ToTable("FrogModel");
                });

            modelBuilder.Entity("EquipmentModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("FrogId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FrogId");

                    b.HasIndex("ItemId");

                    b.ToTable("Equipment");
                });

            modelBuilder.Entity("FightModel", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Account1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Account2Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frog1Id")
                        .HasColumnType("TEXT");

                    b.Property<string>("Frog2Id")
                        .HasColumnType("TEXT");

                    b.Property<int>("Round")
                        .HasColumnType("INTEGER");

                    b.Property<string>("WinnerId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Account1Id");

                    b.HasIndex("Account2Id");

                    b.HasIndex("Frog1Id");

                    b.HasIndex("Frog2Id");

                    b.ToTable("Fights");
                });

            modelBuilder.Entity("ItemModel", b =>
                {
                    b.Property<string>("ItemId")
                        .HasColumnType("TEXT");

                    b.Property<int>("BaseAttack")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BaseDefense")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<int>("Rarity")
                        .HasColumnType("INTEGER");

                    b.HasKey("ItemId");

                    b.ToTable("ItemModel");
                });

            modelBuilder.Entity("BojoweZaby.Models.FrogModel", b =>
                {
                    b.HasOne("BojoweZaby.Models.AccountModel", "Account")
                        .WithMany()
                        .HasForeignKey("AccountId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Account");
                });

            modelBuilder.Entity("EquipmentModel", b =>
                {
                    b.HasOne("BojoweZaby.Models.FrogModel", "Frog")
                        .WithMany()
                        .HasForeignKey("FrogId");

                    b.HasOne("ItemModel", "Item")
                        .WithMany()
                        .HasForeignKey("ItemId");

                    b.Navigation("Frog");

                    b.Navigation("Item");
                });

            modelBuilder.Entity("FightModel", b =>
                {
                    b.HasOne("BojoweZaby.Models.AccountModel", "Account1")
                        .WithMany()
                        .HasForeignKey("Account1Id");

                    b.HasOne("BojoweZaby.Models.AccountModel", "Account2")
                        .WithMany()
                        .HasForeignKey("Account2Id");

                    b.HasOne("BojoweZaby.Models.FrogModel", "Frog1")
                        .WithMany()
                        .HasForeignKey("Frog1Id");

                    b.HasOne("BojoweZaby.Models.FrogModel", "Frog2")
                        .WithMany()
                        .HasForeignKey("Frog2Id");

                    b.Navigation("Account1");

                    b.Navigation("Account2");

                    b.Navigation("Frog1");

                    b.Navigation("Frog2");
                });
#pragma warning restore 612, 618
        }
    }
}
